### ISSUE TITLE
Did something change in the US market?

### ISSUE THREAD

**Issue by tfer6** [Dielee/volvo2mqtt#139] opened 2023-11-25 20:46 UTC
**Describe the bug**
Previously... a few versions ago I was able to get most of the sensors working.  I know not all of them work in the US market.  However, either this version or the previous they all stopped.  I have a 2023 xc60 recharge.  I tried spinning this up on a separate machine and the same issue prevailed.  I tried several images prior going back to 1.8.8 to no avail.

'
updateInterval: 300
babelLocale: en_US
TZ: America/Chicago
debug: false
disable_logging: false
mqtt:
  broker: 192.168.1.200
  port: "1883"
  username: ""
  password: ""
volvoData:
  username: ########
  password: ########
  vin: "########"
  vccapikey:
    - ########
  odometerMultiplier: 1
  averageSpeedDivider: 1
  averageFuelConsumptionMultiplier: 1
'

**Version info**:<br>
addon 1.8.19

**Logs**:<br>
Nov 25 14:37:50 volvo2mqtt [107] - INFO: Starting volvo2mqtt version v1.8.19
Nov 25 14:37:51 volvo2mqtt [107] - DEBUG: VCCAPIKEY <REDACTED> works!
Nov 25 14:37:51 volvo2mqtt [107] - DEBUG: [{'key': '<REDACTED>', 'extended': False, 'extended_until': None, 'in_use': False}]
Nov 25 14:37:51 volvo2mqtt [107] - INFO: Using VCCAPIKEY: <REDACTED>
Nov 25 14:37:51 volvo2mqtt [107] - DEBUG: [{'key': '<REDACTED>', 'extended': False, 'extended_until': None, 'in_use': True}]
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Vin: ['<REDACTED>'] found!
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 200
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "a9631d5c-9aaa-4d2d-8968-ae0cb2f5c70d",
  "data" : { }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/fuel
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 200
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "a9631d5c-9aaa-4d2d-8968-ae0cb2f5c70d",
  "data" : { }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 200
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "a9631d5c-9aaa-4d2d-8968-ae0cb2f5c70d",
  "data" : { }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 200
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "a9631d5c-9aaa-4d2d-8968-ae0cb2f5c70d",
  "data" : { }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 200
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "a9631d5c-9aaa-4d2d-8968-ae0cb2f5c70d",
  "data" : { }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 200
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "a9631d5c-9aaa-4d2d-8968-ae0cb2f5c70d",
  "data" : { }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/odometer
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Odometer is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Success! Last Data Update is supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Success! Active schedules is supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/windows
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Window Front Left is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Window Front Right is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Window Rear Left is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Window Rear Right is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Door Front Left is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Door Front Right is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Door Rear Left is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Door Rear Right is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Tailgate is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Engine Hood is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Tank Lid is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Sunroof is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Success! Air Conditioning is supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Lock state is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Success! Force Update Data is supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/location/v1/vehicles/{0}/location
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: {
  "status" : 404,
  "operationId" : "c61b4a1f-970a-4504-8c1f-ac5c30c120a6",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "c61b4a1f-970a-4504-8c1f-ac5c30c120a6",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
  }
}
Nov 25 14:37:52 volvo2mqtt [107] - INFO: Failed, Location is unfortunately not supported by your vehicle.
Nov 25 14:37:52 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/tyres
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Tire Front Left is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Tire Front Right is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Tire Rear Left is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Tire Rear Right is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Engine State is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/statistics
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Average Energy Consumption is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Distance to Empty Battery is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Average Speed is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Hours to Service is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Distance to Service is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:53 volvo2mqtt [107] - INFO: Failed, Time to Service is unfortunately not supported by your vehicle.
Nov 25 14:37:53 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 25 14:37:54 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:54 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:54 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:54 volvo2mqtt [107] - INFO: Failed, Service warning status is unfortunately not supported by your vehicle.
Nov 25 14:37:54 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 25 14:37:54 volvo2mqtt [107] - DEBUG: Response status code: 404
Nov 25 14:37:54 volvo2mqtt [107] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:54 volvo2mqtt [107] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 25 14:37:54 volvo2mqtt [107] - INFO: Failed, Washer Fluid Level warning is unfortunately not supported by your vehicle.
Nov 25 14:37:54 volvo2mqtt [107] - INFO: Success! API Backend status is supported by your vehicle.

**Comment by Dielee** [comment] 2023-11-25 22:28
Duplicate of #136. Those are API changes.

**Closed by Dielee** 2023-11-25 22:28 UTC
