### ISSUE TITLE
Missing Battery Charge Level % for EX30

### ISSUE THREAD

**Issue by jackyoung1** [Dielee/volvo2mqtt#223] opened 2024-08-17 11:26 UTC
**Describe the bug**
Although documentation suggests it is returned, I cant seem to see the remaining charge % level as an entity, I can only see the remaining miles range

**To Reproduce**:<br>
1 - look in entities

**Expected behavior**:<br>
To see an entity for remaining charge %
volvo suggests this value is available for all AAOS cars via enregy api (https://developer.volvocars.com/apis/energy/v1/overview/#availability) using endpoint - https://api.volvocars.com/energy/v1/vehicles/{vin}/recharge-status/battery-charge-level

**Version info**:<br>
Homeasistant green latest version and latest versions of MQTT and volvo2MQTT addons

**Logs**:<br>
Enable the debug option and upload your logfile here. <br>
<b>Aug 17 12:20:44 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.9.6
Aug 17 12:20:44 volvo2mqtt [106] - INFO: Using login from token file
Aug 17 12:20:44 volvo2mqtt [106] - INFO: Refreshing credentials
Aug 17 12:20:45 volvo2mqtt [106] - INFO: Using VCCAPIKEY: a56799a5412949d9910cba64a49df6b9
Aug 17 12:20:45 volvo2mqtt [106] - INFO: Vin: ['YV12ZEM10RS081866'] found!
Aug 17 12:20:45 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "8398e4bc-bbf1-4bf1-94c8-245a6cb1b2cf",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Car model is not supported"
  }
}
Aug 17 12:20:45 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Battery Capacity is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "8398e4bc-bbf1-4bf1-94c8-245a6cb1b2cf",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Car model is not supported"
  }
}
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "8398e4bc-bbf1-4bf1-94c8-245a6cb1b2cf",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Car model is not supported"
  }
}
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "8398e4bc-bbf1-4bf1-94c8-245a6cb1b2cf",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Car model is not supported"
  }
}
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "8398e4bc-bbf1-4bf1-94c8-245a6cb1b2cf",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Car model is not supported"
  }
}
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "8398e4bc-bbf1-4bf1-94c8-245a6cb1b2cf",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Car model is not supported"
  }
}
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Odometer is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Last Data Update is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Active schedules is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Window Front Left is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Window Front Right is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Window Rear Left is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Window Rear Right is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Door Front Left is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Door Front Right is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Door Rear Left is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Door Rear Right is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Tailgate is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Engine Hood is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Tank Lid is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Sunroof is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Air Conditioning is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Lock state is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Force Update Data is supported by your vehicle.
Aug 17 12:20:46 volvo2mqtt [106] - INFO: Success! Location is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Tire Front Left is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Tire Front Right is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Tire Rear Left is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Tire Rear Right is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Engine State is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Failed, Average Energy Consumption is unfortunately not supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Failed, Average Speed is unfortunately not supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Failed, Hours to Service is unfortunately not supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Distance to Service is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Time to Service is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Service warning status is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! API Backend status is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Success! Update Interval is supported by your vehicle.
Aug 17 12:20:47 volvo2mqtt [106] - INFO: Failed, Warnings is unfortunately not supported by your vehicle.
Aug 17 12:20:50 volvo2mqtt [106] - INFO: Sending mqtt update...
Aug 17 12:20:50 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by Dielee** [comment] 2024-08-17 11:27
Duplicate of #221

**Closed** 2024-08-17 11:27 UTC
